name = "NLOptControl"
uuid = "290757bd-39a7-5095-97bb-ca0f46959724"
version = "0.0.1"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
Hiccup = "9fb69e20-1954-56bb-a84f-559cc56a8ff7"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ReverseDiffSparse = "89212889-6d3f-5f97-b412-7825138f6c9c"

[compat]
CSV = "≥ 0.2.4"
Colors = "≥ 0.8.2"
DataFrames = "≥ 0.11.0"
DiffEqBase = "≥ 3.13.3"
FastGaussQuadrature = "≥ 0.3.2"
GR = "≥ 0.35.0"
Hiccup = "≥ 0.1.1"
Interpolations = "≥ 0.8.0"
Ipopt = "≥ 0.4.3"
JuMP = "≥ 0.20.0"
MathOptInterface = "≥ 0.9.7"
OrdinaryDiffEq = "≥ 3.21.0"
Plots = "≥ 0.17.4"
ReverseDiffSparse = "≥ 0.8.6"
julia = "≥ 1.0.0"
